// Code generated by goctl. DO NOT EDIT!
// Source: favorite.proto

package server

import (
	"context"

	"bwcxgdz/dousheng/service/favorite/rpc/internal/logic"
	"bwcxgdz/dousheng/service/favorite/rpc/internal/svc"
	"bwcxgdz/dousheng/service/favorite/rpc/proto"
)

type FavoriteServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedFavoriteServer
}

func NewFavoriteServer(svcCtx *svc.ServiceContext) *FavoriteServer {
	return &FavoriteServer{
		svcCtx: svcCtx,
	}
}

func (s *FavoriteServer) GetFavoriteVideoListById(ctx context.Context, in *proto.IdRequest) (*proto.VideoIdListResponse, error) {
	l := logic.NewGetFavoriteVideoListByIdLogic(ctx, s.svcCtx)
	return l.GetFavoriteVideoListById(in)
}

func (s *FavoriteServer) FavoriteAction(ctx context.Context, in *proto.ActionRequest) (*proto.ActionResponse, error) {
	l := logic.NewFavoriteActionLogic(ctx, s.svcCtx)
	return l.FavoriteAction(in)
}
