// Code generated by goctl. DO NOT EDIT.
package types

type FollowListRequest struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type FollowListResponse struct {
	StatusCode int64       `json:"status_code"`
	StatusMsg  string      `json:"status_msg"`
	UserList   []*UserInfo `json:"user_list"`
}

type FollowerListRequest struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type FollowerListResponse struct {
	StatusCode int64       `json:"status_code"`
	StatusMsg  string      `json:"status_msg"`
	UserList   []*UserInfo `json:"user_list"`
}

type RelationRequest struct {
	Token      string `json:"token"`
	ToUserId   int64  `json:"to_user_id"`
	ActionType int32  `json:"action_type"`
}

type RelationResponse struct {
	StatusCode int64  `json:"status_code"`
	StatusMsg  string `json:"status_msg"`
}

type UserInfo struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}
