// Code generated by goctl. DO NOT EDIT!
// Source: comment.proto

package server

import (
	"context"

	"rpc/internal/logic"
	"rpc/internal/svc"
	"rpc/proto"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) GetCommentListById(ctx context.Context, in *proto.VideoIdRequest) (*proto.CommentListResponse, error) {
	l := logic.NewGetCommentListByIdLogic(ctx, s.svcCtx)
	return l.GetCommentListById(in)
}

func (s *CommentServer) CommentAction(ctx context.Context, in *proto.ActionRequest) (*proto.ActionResponse, error) {
	l := logic.NewCommentActionLogic(ctx, s.svcCtx)
	return l.CommentAction(in)
}
