// Code generated by goctl. DO NOT EDIT!
// Source: video.proto

package server

import (
	"context"

	"bwcxgdz/dousheng/service/video/rpc/internal/logic"
	"bwcxgdz/dousheng/service/video/rpc/internal/svc"
	"bwcxgdz/dousheng/service/video/rpc/proto"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) Feed(ctx context.Context, in *proto.FeedRequest) (*proto.FeedListResponse, error) {
	l := logic.NewFeedLogic(ctx, s.svcCtx)
	return l.Feed(in)
}

func (s *VideoServer) Publish(ctx context.Context, in *proto.VideoInfoRequest) (*proto.PublishResponse, error) {
	l := logic.NewPublishLogic(ctx, s.svcCtx)
	return l.Publish(in)
}

func (s *VideoServer) PublishVideoList(ctx context.Context, in *proto.IdRequest) (*proto.VideoListResponse, error) {
	l := logic.NewPublishVideoListLogic(ctx, s.svcCtx)
	return l.PublishVideoList(in)
}

func (s *VideoServer) GetVideoInfoById(ctx context.Context, in *proto.IdRequest) (*proto.VideoInfoResponse, error) {
	l := logic.NewGetVideoInfoByIdLogic(ctx, s.svcCtx)
	return l.GetVideoInfoById(in)
}
