// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	favoriteFieldNames          = builder.RawFieldNames(&Favorite{})
	favoriteRows                = strings.Join(favoriteFieldNames, ",")
	favoriteRowsExpectAutoSet   = strings.Join(stringx.Remove(favoriteFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	favoriteRowsWithPlaceHolder = strings.Join(stringx.Remove(favoriteFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"
	videoIds                    = "`video_id`"
	cacheFavoriteIdPrefix       = "cache:favorite:id:"
)

type (
	favoriteModel interface {
		Insert(ctx context.Context, data *Favorite) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Favorite, error)
		Update(ctx context.Context, newData *Favorite) error
		Delete(ctx context.Context, id int64) error
		DeleteByUserIdAndVideoId(ctx context.Context, userId int64, videoId int64) error
		FindListByUserId(ctx context.Context, userId int64) ([]int64, error)
	}

	defaultFavoriteModel struct {
		sqlc.CachedConn
		table string
	}

	Favorite struct {
		Id        int64     `db:"id"`
		CreatedAt time.Time `db:"created_at"`
		UserId    int64     `db:"user_id"`
		VideoId   int64     `db:"video_id"`
	}
)

func newFavoriteModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultFavoriteModel {
	return &defaultFavoriteModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`favorite`",
	}
}

func (m *defaultFavoriteModel) Delete(ctx context.Context, id int64) error {
	favoriteIdKey := fmt.Sprintf("%s%v", cacheFavoriteIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, favoriteIdKey)
	return err
}

func (m *defaultFavoriteModel) DeleteByUserIdAndVideoId(ctx context.Context, userId int64, videoId int64) error {
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `user_id` = ? and `video_id` = ? ", m.table)
		return conn.ExecCtx(ctx, query, userId, videoId)
	})
	return err
}

func (m *defaultFavoriteModel) FindOne(ctx context.Context, id int64) (*Favorite, error) {
	favoriteIdKey := fmt.Sprintf("%s%v", cacheFavoriteIdPrefix, id)
	var resp Favorite
	err := m.QueryRowCtx(ctx, &resp, favoriteIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", favoriteRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) FindListByUserId(ctx context.Context, userId int64) ([]int64, error) {

	var videoId []int64
	err := m.QueryRowsNoCacheCtx(ctx, &videoId,
		fmt.Sprintf("select %s from %s where `id` = ? limit 1", videoIds, m.table), userId)
	switch err {
	case nil:
		return videoId, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) Insert(ctx context.Context, data *Favorite) (sql.Result, error) {
	favoriteIdKey := fmt.Sprintf("%s%v", cacheFavoriteIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, favoriteRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreatedAt, data.UserId, data.VideoId)
	}, favoriteIdKey)
	return ret, err
}

func (m *defaultFavoriteModel) Update(ctx context.Context, data *Favorite) error {
	favoriteIdKey := fmt.Sprintf("%s%v", cacheFavoriteIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, favoriteRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.CreatedAt, data.UserId, data.VideoId, data.Id)
	}, favoriteIdKey)
	return err
}

func (m *defaultFavoriteModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheFavoriteIdPrefix, primary)
}

func (m *defaultFavoriteModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", favoriteRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFavoriteModel) tableName() string {
	return m.table
}
