// Code generated by goctl. DO NOT EDIT!
// Source: relation.proto

package server

import (
	"context"

	"bwcxgdz/dousheng/service/relation/rpc/internal/logic"
	"bwcxgdz/dousheng/service/relation/rpc/internal/svc"
	"bwcxgdz/dousheng/service/relation/rpc/proto"
)

type RelationServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedRelationServer
}

func NewRelationServer(svcCtx *svc.ServiceContext) *RelationServer {
	return &RelationServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationServer) RelationAction(ctx context.Context, in *proto.RelationActionRequest) (*proto.ActionResponse, error) {
	l := logic.NewRelationActionLogic(ctx, s.svcCtx)
	return l.RelationAction(in)
}

func (s *RelationServer) GetFollowList(ctx context.Context, in *proto.IdRequest) (*proto.UserIdListResponse, error) {
	l := logic.NewGetFollowListLogic(ctx, s.svcCtx)
	return l.GetFollowList(in)
}

func (s *RelationServer) GetFollowerList(ctx context.Context, in *proto.IdRequest) (*proto.UserIdListResponse, error) {
	l := logic.NewGetFollowerListLogic(ctx, s.svcCtx)
	return l.GetFollowerList(in)
}
