// Code generated by goctl. DO NOT EDIT.
package types

type CommentListRequest struct {
	VideoId int64  `json:"video_id"`
	Token   string `json:"token"`
}

type CommentListResponse struct {
	StatusCode int64          `json:"status_code"`
	StatusMsg  string         `json:"status_msg"`
	Comment    []*CommentInfo `json:"comment"`
}

type CommentRequest struct {
	Token       string `json:"token"`
	VideoId     int64  `json:"video_id"`
	ActionType  int32  `json:"action_type"`
	CommentText string `json:"comment_text"`
	CommentId   int64  `json:"comment_id"`
}

type CommentResponse struct {
	StatusCode int64          `json:"status_code"`
	StatusMsg  string         `json:"status_msg"`
	Comment    []*CommentInfo `json:"comment"`
}

type CommentInfo struct {
	Id         int64    `json:"id"`
	User       UserInfo `json:"user"`
	Content    string   `json:"content"`
	CreateDate string   `json:"create_date"`
}

type UserInfo struct {
	Id            int64  `json:"id"`
	Name          string `json:"name"`
	FollowCount   int64  `json:"follow_count"`
	FollowerCount int64  `json:"follower_count"`
	IsFollow      bool   `json:"is_follow"`
}
